### ISSUE TITLE
atom feeds aren't valid and their items lack the updated attribute

### ISSUE THREAD

**Issue by cooky-cook** [vinc/news.vinc.cc#56]
Hey,

first of all thanks for the amazing work - providing feeds for websites that don't offer them is very useful, I believe it's one of the best ways of getting your news unlike all the social media bubble nonsense everyone seems to like right now.

I've got a small issue - the wikipedia feed's items (specifically https://news.vinc.cc/search.atom?q=w%2Bevents%2Btime%3Aweek) never get updated in my feed reader once they are fetched. I use Inoreader. Their support told me it could be due to the feed not being valid - see results here:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnews.vinc.cc%2Fsearch.atom%3Fq%3Dw%2Bevents%2Btime%253Aweek

After skimming the atom feed spec, another issue could be that items lack the updated attribute (they only have the published attribute) which could be the real issue.

I'm not any good at ruby, otherwise I'd have a try at fixing this myself. Anyway, if you have a bit of time I'd really appreciate if you could try to fix this so that feed items get updated properly.

Thank you.

**Comment by vinc** [comment]
Thank you very much for taking the time to report this issue, I'll add what's needed to the feed!

**Comment by vinc** [comment]
I started a PR for that here: https://github.com/vinc/news.vinc.cc/pull/57

**Comment by vinc** [comment]
Got the PR deployed in production, missed something about the content type and fixed it here: https://github.com/vinc/news.vinc.cc/pull/63

I'll be deploying the fix in production shortly.

**Comment by cooky-cook** [comment]
Hi,

thanks for deploying your fixes into production. Unfortunately, it seems feed validity was not the actual issue - the articles still won't update properly on Inoreader. Here's Inoreader's support final answer:

> We are detecting articles' content and titles for differences. If there is only one symbol difference in their titles or content, they will be updated.
> 
> But please note that we have a protection system for updated articles - each article will update up to 3 times. If this article updates 4th time it will not appear as updated.
> 
> So if your newly updated articles meet these criteria they will appear as updated.

Due to this arbitrary limitation, there's nothing we can do about it, I think.

**Comment by vinc** [comment]
I see, that's unfortunate because articles are updated a lot on Wikipedia, and they are often created before there is any content to put in them.

A solution for Inoreader would be to offer a manual refresh, or a frequency setting, so that you decide when to update the feed. In Newsboat, a CLI RSS reader, I tend to refresh once per day and read that particular feed with one day lag, ignoring the incomplete article of the current day.
